version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SOLAR_MONITOR_BASE_URL=${SOLAR_MONITOR_BASE_URL}
      - SOLAR_MONITOR_AUTH_USER=${SOLAR_MONITOR_AUTH_USER}
      - SOLAR_MONITOR_AUTH_PW=${SOLAR_MONITOR_AUTH_PW}
      - SOLAR_MONITOR_FRAME_ANCESTORS=${SOLAR_MONITOR_FRAME_ANCESTORS}
